export const countryCodes: { [key: string]: string } = {
  Algeria: 'DZ',
  Bahrain: 'BH',
  Chad: 'TD',
  Djibouti: 'DJ',
  Egypt: 'EG',
  Iraq: 'IQ',
  Jordan: 'JO',
  Kuwait: 'KW',
  Lebanon: 'LB',
  Libya: 'LY',
  Mali: 'ML',
  Mauritania: 'MR',
  Morocco: 'MA',
  Oman: 'OM',
  Palestine: 'PS',
  Qatar: 'QA',
  'Saudi Arabia': 'SA',
  Sudan: 'SD',
  Syria: 'SY',
  Tunisia: 'TN',
  'United Arab Emirates': 'AE',
  Yemen: 'YE',
};
